"""Tests for engine/parsers.py"""

import pytest
from engine.parsers import parse_file, _infer_zygosity_from_genotype, _is_failed_genotype


# ---------------------------------------------------------------------------
# 23andMe format
# ---------------------------------------------------------------------------

_23ANDME_CONTENT = b"""# This data file generated by 23andMe
# rsid\tchromosome\tposition\tgenotype
rs429358\t19\t44908684\tCT
rs7412\t19\t44908822\tCC
rs80357906\t17\t41276045\tAG
rs1234\t1\t100000\t--
i7001348\t1\t200000\tTT
rs9999\t1\t300000\tDI
"""


def test_23andme_parses_standard_variants():
    variants = parse_file(_23ANDME_CONTENT, "test.txt")
    rsids = [v["rsid"] for v in variants]
    assert "rs429358" in rsids
    assert "rs7412"   in rsids
    assert "rs80357906" in rsids


def test_23andme_skips_internal_ids():
    variants = parse_file(_23ANDME_CONTENT, "test.txt")
    assert not any(v["rsid"] == "i7001348" for v in variants)


def test_23andme_skips_failed_calls():
    variants = parse_file(_23ANDME_CONTENT, "test.txt")
    # rs1234 has genotype "--" — should be dropped
    assert not any(v["rsid"] == "rs1234" for v in variants)


def test_23andme_skips_indel_markers():
    variants = parse_file(_23ANDME_CONTENT, "test.txt")
    # rs9999 has genotype "DI" — should be dropped
    assert not any(v["rsid"] == "rs9999" for v in variants)


def test_23andme_variant_type():
    variants = parse_file(_23ANDME_CONTENT, "test.txt")
    assert all(v["variant_type"] == "rsid_only" for v in variants)


def test_23andme_zygosity_heterozygous():
    variants = parse_file(_23ANDME_CONTENT, "test.txt")
    ct = next(v for v in variants if v["rsid"] == "rs429358")
    assert ct["zygosity"] == "heterozygous"


def test_23andme_zygosity_homozygous_alt():
    variants = parse_file(_23ANDME_CONTENT, "test.txt")
    cc = next(v for v in variants if v["rsid"] == "rs7412")
    assert cc["zygosity"] == "homozygous_alt"


# ---------------------------------------------------------------------------
# Plain rsID list
# ---------------------------------------------------------------------------

_RSID_LIST = b"rs429358\nrs7412\nrs80357906\n"


def test_rsid_list_parsing():
    variants = parse_file(_RSID_LIST, "test.txt")
    assert len(variants) == 3
    assert all(v["variant_type"] == "rsid_only" for v in variants)


# ---------------------------------------------------------------------------
# CSV format
# ---------------------------------------------------------------------------

_CSV_CONTENT = b"""chrom,pos,ref,alt,rsid
19,44908684,T,C,rs429358
17,41276045,A,G,rs80357906
"""


def test_csv_parsing():
    variants = parse_file(_CSV_CONTENT, "test.csv")
    assert len(variants) == 2
    assert all(v["variant_type"] == "coordinate" for v in variants)


def test_csv_chromosome_normalized():
    variants = parse_file(_CSV_CONTENT, "test.csv")
    chroms = {v["chrom"] for v in variants}
    # Should not contain "chr" prefix
    assert not any(c.startswith("chr") for c in chroms if c)


# ---------------------------------------------------------------------------
# Zygosity inference helpers
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("genotype,ref,expected", [
    ("CT", "C", "heterozygous"),
    ("TC", "T", "heterozygous"),
    ("TT", "C", "homozygous_alt"),
    ("TT", "T", "homozygous_ref"),
    ("CC", None, "homozygous_alt"),
    ("AA", None, "homozygous_alt"),
    ("AC", None, "heterozygous"),
    ("A",  None, "unknown"),
    ("",   None, "unknown"),
])
def test_infer_zygosity(genotype, ref, expected):
    assert _infer_zygosity_from_genotype(genotype, ref) == expected


# ---------------------------------------------------------------------------
# Failed genotype filter
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("genotype,expected", [
    ("--",  True),
    ("NN",  True),
    (".",   True),
    ("-",   True),
    ("DI",  True),
    ("II",  True),
    ("DD",  True),
    ("DT",  True),  # contains D
    ("TIT", True),  # contains I and >2 chars
    ("CT",  False),
    ("TT",  False),
    ("AC",  False),
    ("A",   False),
])
def test_is_failed_genotype(genotype, expected):
    assert _is_failed_genotype(genotype) == expected


# ---------------------------------------------------------------------------
# Unsupported format
# ---------------------------------------------------------------------------

def test_unsupported_format_raises():
    with pytest.raises(ValueError, match="Unsupported"):
        parse_file(b"data", "test.bam")
